//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge3.Data.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int Id { get; set; }
        public string UserCode { get; set; }
        public System.DateTime CrationDate { get; set; }
        public int DueDays { get; set; }
        public decimal Value { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public byte[] LineVersion { get; set; }
    
        public virtual User User { get; set; }
    }
}
