//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge3.Data.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int Id { get; set; }
        public int ProductTypeId { get; set; }
        public string ProductCode { get; set; }
        public string UserCode { get; set; }
        public System.DateTime RentDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> DevolutionDate { get; set; }
        public byte[] LineVersion { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual User User { get; set; }
    }
}
