//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge3.Data
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations.Schema;
    using Infrastructure.Data;
    
    #pragma warning disable 1591
    
    [Serializable]
    public partial class Fine: IObjectState
    {
        [NotMapped]
        public ObjectState ObjectState { get; set; }
        public int Id { get; set; }
        public string UserCode { get; set; }
        public System.DateTime CrationDate { get; set; }
        public int DueDays { get; set; }
        public decimal Value { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public byte[] LineVersion { get; set; }
    
        public virtual User User { get; set; }
    }
    #pragma warning restore 1591
}
