//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge3.Data
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations.Schema;
    using Infrastructure.Data;
    
    #pragma warning disable 1591
    
    [Serializable]
    public partial class ProductType: IObjectState
    {
        [NotMapped]
        public ObjectState ObjectState { get; set; }
        public ProductType()
        {
            this.Books = new HashSet<Book>();
            this.Rents = new HashSet<Rent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool CanBeRented { get; set; }
        public int RentPeriod { get; set; }
        public decimal FineValue { get; set; }
        public int MaxRenting { get; set; }
        public byte[] LineVersion { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<Rent> Rents { get; set; }
    }
    #pragma warning restore 1591
}
